Repository ZennoHelpers/Snippets, pull requests merged in 2019-10, with the labels that each got.

#20 Получение данных методами ZP.cs
  Сниппеты/[JSON]/Получение данных методами ZP.cs
Labels: new snippets

#27 Rename JS directory to JavaScript
  Сниппеты/[JavaScript]/[Дата, Время]/unixtime.js
  Сниппеты/[JavaScript]/[Страница]/Высота с учетом прокрутки.js
  Сниппеты/[JavaScript]/[Страница]/Изменение прокрутки.js
  Сниппеты/[JavaScript]/[Страница]/Отслеживание изменения координат элемента.js
  Сниппеты/[JavaScript]/[Страница]/Получение координат.js
  Сниппеты/[JavaScript]/[Страница]/Получение элемента страницы.js
  Сниппеты/[JavaScript]/Проверка наличие вложенных свойств.js
  Сниппеты/[JavaScript]/Расчёт формулы в строке.js
Labels: Hacktoberfest, code improvement

#28 Перенёс сниппеты для управления настройками FF в поддиректорию
  Сниппеты/[Браузер]/[Настройки FireFox]/Включить проигрыватель видеофайлов.cs
  Сниппеты/[Браузер]/[Настройки FireFox]/Отключение кэша.cs
  Сниппеты/[Браузер]/[Настройки FireFox]/Отключить Content Security Policy.cs
Labels: Hacktoberfest, code improvement

#29 Получить все ссылки со страницы по домену
  Сниппеты/[Браузер]/Получить все ссылки со страницы по домену.cs
Labels: Hacktoberfest, new snippets

#30 Случайный регистр
  Сниппеты/[Текст]/Случайный регистр.cs
Labels: Hacktoberfest, new snippets

#31 Замер времени выполнения кода (для отладки)
  Сниппеты/[Отладка]/Замер времени выполнения кода.cs
Labels: Hacktoberfest, new snippets

#32 Корректнее использовать ActiveTab
  Сниппеты/[Капчи]/[ReCaptcha]/Проверка присутствия на странице.cs
Labels: Hacktoberfest, code improvement

#33 Замена недопустимых символов в имени файла
  Сниппеты/[Директории, Файлы]/Замена недопустимых символов в имени файла.cs
Labels: Hacktoberfest, new snippets

#34 Выбрать случайный элемент из списка и кликнуть
  Сниппеты/[Браузер]/Выбрать случайный элемент из списка и кликнуть.cs
Labels: Hacktoberfest, new snippets
