Repository ZennoHelpers/Snippets, pull requests merged in 2019-09, with the labels that each got.

#5 Изменил и адаптировал сниппет
  Сниппеты/[JSON]/Форматирование Json.cs
Labels: code improvement

#8 formOKCancel форма OK Отмена
  Сниппеты/[Браузер]/Перезагрузить страницу.cs
  Сниппеты/[Сторонний GUI]/Окно ввода строки.cs
Labels: new snippets

#7 Добавлен сниппеты для работы со списками
  Сниппеты/[Списки]/Вернуть количество элементов в списке проекта.cs
  Сниппеты/[Списки]/Взятие первой строки с удалением и добавлением в конец строки.cs
  Сниппеты/[Списки]/Взять диапозон строк из файла и вернуть строку добавив разделитель.cs
  Сниппеты/[Списки]/Вычитание одного списка из другого.cs
  Сниппеты/[Списки]/Вычитание строк одного файла из другого.cs
  Сниппеты/[Списки]/Добавить в список элемент из переменной проекта.cs
  Сниппеты/[Списки]/Добавление всех вхождений из текста в список.cs
  Сниппеты/[Списки]/Замена элементов в списке по регулярному выражению.cs
  Сниппеты/[Списки]/Из списка в список по Regex.cs
  Сниппеты/[Списки]/Очистка списков проекта.cs
  Сниппеты/[Списки]/Перемешать список.cs
  Сниппеты/[Списки]/Получить индекс элемента в списке.cs
  Сниппеты/[Списки]/Проверка содержит ли список какую-то конкретную строку.cs
  Сниппеты/[Списки]/Удаление из списка по Regex.cs
Labels: new snippets

#9 Парочка сниппетов
  Сниппеты/[Запросы]/Получить IP по домену.cs
  Сниппеты/[Логика]/Прерываемая пауза в секундах.cs
  Сниппеты/[Переменные]/Создание переменной Zenno из кода и задание ей значения.cs
  Сниппеты/[Текст]/Генерация случайного англоязычного пароля.cs
  Сниппеты/Фиксировать при ошибке source, dom, переменные, лог и скриншот.cs
Labels: new snippets

#12 Добавил несколько новых сниппетов
  Сниппеты/[Даты, Время]/Получить unixtime.cs
  Сниппеты/[Даты, Время]/Разница в днях между двумя датами.cs
  Сниппеты/[Капчи]/[ReCaptcha]/Проверка присутствия на странице.cs
Labels: new snippets

#13 Добавлены сниппеты работы с текстом
  Сниппеты/[Картинки]/Преобразование текста в изображение.cs
  Сниппеты/[Текст]/Вставка ключей в текст из списка в случайном порядке.cs
  Сниппеты/[Текст]/Изменение первой буквы первого слова на заглавную.cs
  Сниппеты/[Текст]/Изменение первых букв слова с прописных в строчные.cs
  Сниппеты/[Текст]/Проверка на наличие кириллицы в тексте или переменной.cs
  Сниппеты/[Текст]/Разбиение текста на файлы по разделителю.cs
  Сниппеты/[Текст]/Разделить строку на части по разделителю.cs
Labels: new snippets

#14 Удалить пустые строки
  Сниппеты/[Текст]/Удаление пустых строк из файла.cs
Labels: new snippets

#15 Улучшил readme
  README.md
Labels: documentation

#16 Примеры для работы с картинками
  Сниппеты/[Картинки]/base64 в bitmap.cs
  Сниппеты/[Картинки]/Получение значений пикселя.cs
Labels: new snippets

#18 IP в Int и обратно
  Сниппеты/[Прокси]/IP в Int и обратно.cs
Labels: new snippets

#23 Update README.md
  README.md
Labels: documentation

#19 Новые сниппеты + правки старых
  Сниппеты/[JS]/[Дата, Время]/unixtime.js
  Сниппеты/[JS]/[Страница]/Высота с учетом прокрутки.js
  Сниппеты/[JS]/[Страница]/Изменение прокрутки.js
  Сниппеты/[JS]/[Страница]/Отслеживание изменения координат элемента.js
  Сниппеты/[JS]/[Страница]/Получение координат.js
  Сниппеты/[JS]/[Страница]/Получение элемента страницы.js
  Сниппеты/[JS]/Проверка наличие вложенных свойств.js
  Сниппеты/[JS]/Расчёт формулы в строке.js
  Сниппеты/[Дата, Время]/Получить unixtime.cs
  Сниппеты/[Дата, Время]/Разница в днях между двумя датами.cs
  Сниппеты/[Логика]/[Блокировка между потоками, шаблонами]/Объекты для синхронизации шаблонов.cs
  Сниппеты/[Логика]/Вызвать ошибку с описанием.cs
  Сниппеты/[Списки]/Вернуть позицию элемента.cs
  Сниппеты/[Списки]/Добавить в список.cs
  Сниппеты/[Списки]/Получить количество элементов.cs
  Сниппеты/[Списки]/Удаление дублей в списке.cs
  Сниппеты/[Текст]/Смена кодировки строки.cs
  Сниппеты/Изменить настройки ZennoPoster'а.cs
Labels: new snippets

#21 Добавлены сниппеты работы с датами
  Сниппеты/[Даты, Время]/Дата и время в разных форматах.cs
  Сниппеты/[Даты, Время]/Из DateTime в UnixTime.cs
  Сниппеты/[Даты, Время]/Из UnixTime в DateTime.cs
  Сниппеты/[Даты, Время]/Сравнение дат.cs
  Сниппеты/[Даты, Время]/Таймер пройденого времени в UnixTime.cs
  Сниппеты/[Даты, Время]/Таймер пройденого времени по дате.cs
  Сниппеты/[Переменные]/Подсчёт количества символов в переменной.cs
  Сниппеты/[Переменные]/Получить список всех переменных проекта.cs
  Сниппеты/[Переменные]/Процент от числа.cs
  Сниппеты/[Переменные]/Текст или строку из UTF16 в UTF8.cs
  Сниппеты/[Переменные]/Шифрование строки в SHA1.cs
Labels: new snippets

#10 Create Путь до директории проекта.cs
  Сниппеты/[Директории, Файлы]/Путь до директории проекта.cs
Labels: new snippets

#11 Create копирование файла.cs
  Сниппеты/[Директории, Файлы]/Копирование файла.cs
Labels: new snippets

#25 Преобразование доменов РФ в пункикод
  Сниппеты/[Запросы]/Преобразование доменов РФ в punycode.cs
Labels: new snippets

#26 Добавлены сниппеты работы с GUI
  Сниппеты/[Сторонний GUI]/Создание формы с кнопками Далее и Обновить страницу.cs
  Сниппеты/[Сторонний GUI]/Создание формы с полем ввода.cs
  Сниппеты/[Сторонний GUI]/Создать диалог Да или Нет с автозакрытием.cs
  Сниппеты/[Сторонний GUI]/Создать диалог Да или Нет.cs
  Сниппеты/[Сторонний GUI]/Создать форму с чекбоксом.cs
Labels: new snippets
